_posts/tommytester/2018-05-17-tommytester-first-post.md
I've added my very first post ever here!
=> tommytester's first post

_posts/scylarmartin/2018-05-17-scylarmartin-first-post.md
first post on summer python class
=> scylarmartin's first post

_posts/ponderm/2018-05-17-ponderm-first-post.md
=> ponderm created their first post

_posts/hollaATyacodegirl/2018-05-17-hollaATyacodegirl-first-post.md
I added a post about hollaATyacodegirl and her Python experience.
=> Created hollaATyacodegirl's first post!

_posts/aravind/2018-05-17-aravind-first-post.md
=> Shout out to My New Classmates!

_posts/Kevin-Kao/2018-05-17-kevin-kao-first-post.md
Hello world! This is Kevin. I'm excited to be here!
=> Kevin's first post

_posts/TCarmon/2018-05-17-TCarmon-first-post.md
Submitting my post for our Github basics class assignment.
=> Tia's first post

_posts/rachelanniexo/2018-05-17-rachelanniexo-first-post.md
Hi! This is just a first post I created with a little info about myself.
=> Created first post for Rachel Anne

_posts/Kevin-Kao/2018-05-17-kevin-kao-first-post.md
I've added my new self-introduction.
=> Kevin's very fist post

_post/scylarmartin05-21-2018/first reflection
=> scylarmartin's first reflection

_posts/rachelanniexo/2018-05-21-rachelanniexo-first-reflection.md
This is Rachel Anne's first reflection for INLS 560. It is mostly in regards to relief that Python seems to be easier than Java, but does include some mild frustration with setting input as int/float.
=> Rachel Anne's first reflection

_posts/hollaATyacodegirl/2018-05-20-hollaATyacodegirl-first-reflection.md
I added hollaATyacodegirl's First Reflection on the exercises in Chapter 2.
=> Added hollaATyacodegirl's First Reflection

_posts/Kevin-Kao/2018-05-20-kevin-kao-first-reflection-post.md
I've just completed my reflection on the first class and exercises. 😃
=> This is Kevin's reflection on the first class!

_posts/tommytester/2018-05-21-custom-turtle.md
This was my first time embedding a Trinket in a post!  Yay for interactive code on the Web.
`tina` is my favorite variable
=> Added Tommytester's Custom Turtles exercise and reflection

_post/NobrineCalc/2018-05-21-non-original-custom-turtle, _post/NobrineCalc/2018-05-21-non-original-custom-turtle.md
I got down the basics, but I have some ideas I'm not sure on how to implement. I want to figure this out and make those ideas appear sometime soon.
=> a non original custom turtle exercise and reflection

_posts/rachelanniexo/2018-05-21-rachelanniexo-custom-turtle.md
This post contains an embedded copy of Rachel Anne's Custom Turtle submission and an explanation of how the circles are nested to create the effect of ripples in the water.
=> Embedded Rachel Anne's Custom Turtle

_posts/WildGinger23/2018-05-21-Wildginger23-custom-turtle.md
This is my custom turtle that uses user input to change the color of the background and the turtle.
=> Bennett's custom turtle: Lilypad Escapades

_posts/hollaATyacodegirl/2018-05-21-custom-turtle.md
This post describes my creative process in writing the Custom Turtle program, which took user input to color both the Turtle and the Screen, and then drew fun shapes.
=> Added hollaATyacodegirl's Custom Turtle code

_posts/NobrineCalc/2018-05-21-NobrineCalc's first reflection.md, _posts/NobrineCalc/2018-05-21-NobrineCalc-first-reflection.md
Going through the syntax I found that my initial codes failed. I based my code off a source to learn some proper syntax. An interesting result from the source I found is the revisions to coding in Python such as the raw input change.
https://github.com/adisayoga/p2pu-python-101/blob/master/02.%20Expressions/exercise-2.3.py
=> First Reflection for python experience

_posts/bennettchapman/2018-05-17-bennettchapman-first-post.md
=> Bennett's first post

_posts/ponderm/2018-5-21-ponderm-turtle-exercise.md
This post includes an embed of the program and an image of an example of what the program looks like when it's completed.
=> ponderm is sharing her custom turtle exercise

_posts/Kevin-Kao/2018-05-21-kevin-kao-custom-turtle.md
I have completed my reflection on custom turtle. Any suggestions are welcome 😃
=> This is my reflection on custom turtle.

_posts/hollaATyacodegirl/2018-05-20-hollaATyacodegirl-first-reflection.md
=> added second '---' to YAML header

_posts/WildGinger23/2018-05-22-WildGinger-Logical-Turtle.md
deleting the logical turtle with an incorrect filename
=> delete logical turtle with wrong filename

_posts/TCarmon/2018-05-24-TCarmon-turtle-hack.md
My turtle hack and logical turtle are embedded within this post.
=> TCarmon's turtle hack

_posts/rachelanniexo/2018-05-24-turtlehacks-calendar.md, _posts/rachelanniexo/2018-05-24-turtlehacks.md
fixed the embedding issues for my turtlehack
=> fixed embedding issues

_posts/ponderm/2018-05-24-ponderm-functional-turtle.md
This is due tonight at midnight. Includes both the before and after of a code that used functions to make it easier to read.
=> ponderm posted functional turtle exercise

_posts/draravindrk/2018-05-24-turtle-hacks.md
=> Aravind's Turtle Hack!

_posts/Kevin-Kao/2018-05-29-kevin-kao-Treasure-Hunt.md
This is Kevin's Treasure Hunt. Feel free to comment below!
=> Kevin's Treasure Hunt

_posts/rachelanniexo/2018-05-24-functional-turtle-rachelanniexo.md
This is just a post with the embedded programs for my Custom Turtle and my Refactored Custom Turtle, along with a reflection on what I did,
=> rachelanniexo's functional turtles post

_posts/WildGinger23/2018-05-29-WildGinger23-Queen-Anne-Treasure-Hunt.md
Create the Turtle Hunt post due before class today, this is the pull request for that.
=> Create Queen Anne Turtle Hunt

_posts/hollaATyacodegirl/2018-05-29-hollaATyacodegirl-Treasure-Hunt-Turtles.md
Updated hollaATyacodegirl's Treasure Hunt Turtle exercise with the proper embedded url
=> Updated embed link in Treasure Hunt

_posts/Kevin-Kao/2018-05-24-kevin-kao-functional-turtle.md
I've just reduced my long code by using `def:`! 😉
=> Kevin's functional turtle is here!

_posts/hollaATyacodegirl/05-24-2018-hollaATyacodegirl-Functional-Turtle.md
Added hollaATyacodegirl's reflection on Functional Turtle. Included embeds of Logical Turtle and Functional Turtle trinkets.
=> hollaATyacodegirl's Functional Turtle reflection

_posts/WildGinger23/2018-05-24-WildGinger23-Functional-Turtle.md
In this post I embedded my Functional Turtle.
=> Create Functional Turtle

_posts/WildGinger23/2018-05-29-WildGinger23-Queen-Anne-Treasure-Hunt.md
Updating so that code error message looks like code
=> update Queen Anne Treasure Hunt

_config.yml
Updated hollaATyacodegirl's name, gravatar, twitter, and about sections.
=> Updated hollaATyacodegirl information

_config.yml
Kevin's update on personal info
=> I've updated my info

_config.yml
=> Tia's updates to the config file

_config.yml
and added info about rachel anne
=> updated rachel anne name

_posts/ponderm/2018-06-04-ponderm-clicky-turtle.md
Assignment due before class June 4
=> ponderm created clicky turtle exercise reflection

_posts/TCarmon/2018-06-04-TCarmon-Clicky-Turtle.md
Added an image to a comment then inserted the URL within my post.
=> Updated post to include a link to image

_posts/Kevin-Kao/2018-06-04-kevin-kao-clicky-turtle-exercise.md
Feel free to leave any comment here!
=> Kevin's Clicky Turtle Exercise

_posts/rachelanniexo/2018-06-04-rachelanniexo-clicky-turtles.md
embedded trinkets compare the functionalities of two color-changing turtles, also a description of my thinking process
=> created post for Rachel Anne's clicky turtles

_config.yml
I don't have a twitter, and the website link is fake news.
=> update WildGinger23 information

_config.yml
updated personal info to appear on the people section of the class website
=> ponderm added to her personal info

_posts/TCarmon/2018-06-04-TCarmon-Clicky-Turtle.md
Thanks for the suggestion @ponderm! I've updated the format.
=> Updated the formatting to include headers

_posts/rachelanniexo/2018-06-04-rachelannes-second-reflection.md
Created the second reflection for rachelanniexo, including a little bit of markup and two code snippets
=> rachelanniexo second reflection

_posts/scylarmartin/2018-05-24-scmartin functional turtle.md
i figured the problem i mentioned in the reflection out
=> scylarmartin's function turtle

_config.yml
My name and cheeky blurb were already in there.
=> Add tommy tester's awesome URL

_posts/TCarmon/2018-06-04-TCarmon-Clicky-Turtle.md
Made an edit to the markdown language where I was trying to insert an image.
=> Removed an extra space between ] and image

_posts/ponderm/2018-06-06-ponderm-dictionary-exercise.md
=> ponderm dictionary exercise

_posts/hollaATyacodegirl/2018-06-06-hollaAtyacodegirl-Blackjack-Milestones.md
Rough outline of BlackJack project milestones.
=> Create hollaATyacodegirl's BlackJack milestones

_posts/rachelanniexo/2018-06-07-rachelanniexo-color-milestones.md
in which a checklist is created to be edited and filled out as we go
=> created rachel anne's drawing app milestones

_posts/ponderm/2018-06-11-ponderm-meetup-reflection.md
merging with other pull request
=> ponderm created a meet up reflection

_posts/ponderm/2018-06-11-ponderm-black-jack.md
merging with pre-existing pull request
=> ponderm created black jack assignment

_posts/TCarmon/2018-06-05-TCarmon-Dictionary-Exercise.md
=> Tia's Dictionary Exercise

_posts/ponderm/2018-06-06-ponderm-dictionary-exercise.md, _posts/ponderm/2018-06-06-ponderm-milestones-for-app.md
- app milestone reflection and list
=> ponderm created app milestone post and dictionary exercise

_posts/hollaATyacodegirl/2018-06-06-hollaATyacodegirl-inclass-Dictionary-exercises.md
In-class dictionary exercise from 06-05-2018
=> Create hollaATyacodegirl's Dictionary exercise

_posts/rachelanniexo/2018-06-07-rachelanniexo-dict.md
=> rachel anne's dictionary reflection

_posts/WildGinger23/2018-06-11-WildGinger23-Blackjack-Game.md
This is for the Blackjack game assignment.
=> Create Blackjack Game post

_posts/ponderm/2018-06-11-ponderm-black-jack.md
Updating embed link that wasn't working before
=> fixing embed link for early progress of game

_posts/WildGinger23/2018-06-11-WildGinger23-Project-Idea-and-Work-Plan.md
Here is my project idea, I work with csv files so I am excited to try out this idea.
=> Create Project Idea and Work Plan post

_posts/rachelanniexo/2018-06-11-rachelanniexo-finalplan.md
posted my list, commented out inside a trinket
=> create project idea & work plan for rachel anne

_posts/draravindrk/2018-06-12-draravindrk-class-hack.md
=> Aravind's Class Hack!

_posts/WildGinger23/2018-06-12-WildGinger23-Class-Hack-Remote-Controlled-Turtle-Drone-Array.md
This is the class hack that I have been working on.
=> Create class hack post

_posts/ponderm/2018-06-12-ponderm-class-hack.md
hacked at black jack and refactored it some
=> class hack of black jack

_posts/rachelanniexo/2018-06-12-pepperoni-redo.md
THIS TIME IT PRINTS PEPPERONI AND I COULDN'T BE HAPPIER
=> created classhack for rachel anne

_posts/hollaATyacodegirl/2018-06-12-hollaATyacodegirl-BlackJackwithClasses.md
I attempted to use classes to refactor my BlackJack code.
=> hollaATyacodegirl's BlackJack with Classes

_posts/ponderm/2018-06-14-ponderm-final-projects-update.md
final project updates for class June 14
=> created final project updates pt. 1

_posts/WildGinger23/2018-06-14-WildGinger23-Project-Update-and-Revised-Plan.md
This is my project update and revised plan.
=> Create Project update and Revised plan

_posts/hollaATyacodegirl/2018-06-14-hollaATyacodegirl-Project-Update.md
Project Update and Milestones as of 06-14
=> hollaATyacodegirl's Project Update as of 06-14

_posts/hollaATyacodegirl/2018-06-18-hollaATyacodegirl-Meetup-Reflection.md
hollaATyacodegirl's RTP Python Meetup Reflection
=> hollaATyacodegirl's Meetup Reflection

_posts/draravindrk/2018-06-04-draravindrk-clicky-turtle.md
=> Update Aravind's Clicky Turtle

_posts/rachelanniexo/2018-06-18-reflection-rtp-meetup-beantraders-rachel-anne.md
I attended the same meetup as hollaATyacodegirl and ponderm
=> created meetup reflection for rachelanniexo

_posts/rachelanniexo/2018-06-18-even-more-updated-milestones-rachelanniexo.md
includes past milestones and code snapshot
=> created rachelanne's updated milestones

_posts/hollaATyacodegirl/2018-06-18-hollaATyacodegirl-Final-Project-Update.md
hollaATyacodegirl's Second FInal Project reflection
=> hollaATyacodegirl's Second FInal Project Update

_posts/ponderm/2018-06-18-ponderm-final-project-update.md
Final project updates for June 18 class (LDOC???)
=> ponderm final project update

_posts/TCarmon/2018-06-18-TCarmon-updated-final-milestones.md
Made edits to remove the # character because my pull request failed tests
=> Tia's final project updates-removed # character

_posts/WildGinger23/2018-06-18-WildGinger23-Project-Update-and-Stand-up-Report.md
Here is my project update post, I took running notes over the weekend.
=> Create Project Update post

_posts/TCarmon/2018-06-18-TCarmon-updated-final-milestones.md
Making an edit to fix the pull request not showing up on the website
=> Tia's final project updates

_posts/rachelanniexo/2018-06-20-rachelanniexo-final-get-the-treasure.md
Includes fancy subheaders so readers know what's going on in each section. Code at the very bottom.
=> Created final reflection for rachelanniexo

_posts/WildGinger23/2018-06-20-WildGinger23-Final-Project.md
Here it is, the final project for INLS 560.
=> Bennett's Final Project

_posts/Kevin-Kao/2018-06-20-kevin-kao-final-project.md
=> Kevin's final project

_posts/draravindrk/2018-06-20-aravind-final-project.md
=> Aravind's Final Project - Update 1
